### ISSUE TITLE
DensifyPointCloud fails with memory issues - SIGSEV

### ISSUE THREAD

**Issue by mdaiter** [cdcseacave/openMVS#102]
When running DensifyPointCloud, OpenMVS seems to SIGSEV after completing the fusing points section as it releases memory from the cv::UMat array during the DepthMapsData::FuseDepthMaps() step.

In particular, I've already tried deleting previously generated .dmaps, and I've ensured that I have enough RAM onboard to load all files into memory.

### Specifications like the version of the project, operating system, and hardware
Ubuntu 14.04
OpenCV 3.1.0
OpenMVG 1.0
OpenMVS latest build - without CUDA enabled (and with)

8 Core i7 processor
Nvidia GTX 1080 graphics card
32 GB of RAM

### Steps to reproduce the problem
1. Download this dataset: https://github.com/rperrot/ReconstructionDataSet/tree/master/BurgosPuertaDeLaCoroneria

2. Run the OpenMVG SfM pipeline, with IncrementalSfM and all default parameters (SIFT for descriptor)

3. Export the OpenMVG file to OpenMVS using the OpenMVG2OpenMVS tool provided by OpenMVG

4. Run DensifyPointCloud against the scene.mvs generated by OpenMVG2OpenMVS.

Here's the backtrace:
```
(gdb) run -i outReconstructionLatch/mvs/scene.mvs -o outReconstructionLatch/mvs/scene_dense.mvs
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /home/nomoko/3D/openMVS_build_2/bin/DensifyPointCloud -i outReconstructionLatch/mvs/scene.mvs -o outReconstructionLatch/mvs/scene_dense.mvs
warning: the debug information found in "/lib64/ld-2.19.so" does not match "/lib64/ld-linux-x86-64.so.2" (CRC mismatch).

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
03:10:19 [App     ] Build date: Jul  9 2016, 02:35:47
03:10:19 [App     ] CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
03:10:19 [App     ] RAM: 31.37GB Physical Memory 7.63GB Virtual Memory
03:10:19 [App     ] OS: Linux 3.19.0-64-generic (x86_64)
03:10:19 [App     ] SSE & AVX compatible CPU & OS detected
03:10:19 [App     ] Command line: -i outReconstructionLatch/mvs/scene.mvs -o outReconstructionLatch/mvs/scene_dense.mvs
03:10:20 [App     ] Camera model loaded: platform 0; camera  0; f 0.861x0.861; poses 1
03:10:20 [App     ] Camera model loaded: platform 1; camera  0; f 0.684x0.684; poses 5
03:10:20 [App     ] Camera model loaded: platform 2; camera  0; f 0.742x0.742; poses 1
03:10:20 [App     ] Camera model loaded: platform 3; camera  0; f 230416.517x230416.517; poses 0
03:10:20 [App     ] Camera model loaded: platform 4; camera  0; f 0.756x0.756; poses 1
03:10:20 [App     ] Camera model loaded: platform 5; camera  0; f 0.685x0.685; poses 1
03:10:20 [App     ] warning: uncalibrated image 'images//DPP_0245.JPG'
[New Thread 0x7fffe9611700 (LWP 19788)]
[New Thread 0x7fffe8e10700 (LWP 19789)]
[New Thread 0x7fffe3fff700 (LWP 19790)]
[New Thread 0x7fffe37fe700 (LWP 19791)]
[New Thread 0x7fffe2ffd700 (LWP 19792)]
[New Thread 0x7fffe27fc700 (LWP 19793)]
[New Thread 0x7fffe1ffb700 (LWP 19794)]
03:10:20 [App     ] Image loaded   1: DPP_0246.JPG
03:10:20 [App     ] Image loaded   2: DPP_0247.JPG
03:10:20 [App     ] Image loaded   3: DPP_0248.JPG
03:10:20 [App     ] Image loaded   4: DPP_0249.JPG
03:10:20 [App     ] Image loaded   5: DPP_0250.JPG
03:10:20 [App     ] Image loaded   6: DPP_0251.JPG
03:10:20 [App     ] Image loaded   7: DPP_0252.JPG
03:10:20 [App     ] Image loaded   8: DPP_0253.JPG
03:10:20 [App     ] Image loaded   9: DPP_0254.JPG
03:10:20 [App     ] Scene loaded from interface format (279ms):
	10 images (9 calibrated) with a total of 180.47 MPixels (20.05 MPixels/image)
	17168 points, 0 vertices, 0 faces
[New Thread 0x7fffe17fa700 (LWP 19795)]
[New Thread 0x7fffe0ff9700 (LWP 19796)]
[New Thread 0x7fffdbfff700 (LWP 19797)]
[New Thread 0x7fffdb7fe700 (LWP 19798)]
[New Thread 0x7fffdaffd700 (LWP 19799)]
[New Thread 0x7fffda7fc700 (LWP 19800)]
[New Thread 0x7fffd9ffb700 (LWP 19801)]
[New Thread 0x7fffd109d700 (LWP 19802)]
[New Thread 0x7fffd089c700 (LWP 19803)]
[New Thread 0x7fff97fff700 (LWP 19804)]
[New Thread 0x7fff968f3700 (LWP 19805)]
[New Thread 0x7fff951e7700 (LWP 19806)]
[New Thread 0x7fff949e6700 (LWP 19807)]
[New Thread 0x7fff7ffff700 (LWP 19808)]
[New Thread 0x7fff7e8f3700 (LWP 19809)]
03:10:20 [App     ] Preparing images for dense reconstruction completed: 10 images (422ms)
03:10:20 [App     ] Selecting images for dense reconstruction completed: 9 images (4ms)
[New Thread 0x7fffd97fa700 (LWP 19810)]
[New Thread 0x7fffd8ff9700 (LWP 19811)]
Estimated depth-maps 8 (88.89%, 21s, ETA 2s)...[Thread 0x7fffd8ff9700 (LWP 19811) exited]
Estimated depth-maps 9 (100%, 23s429ms)          
[Thread 0x7fffd97fa700 (LWP 19810) exited]
[New Thread 0x7fffd8ff9700 (LWP 19824)]
[New Thread 0x7fffd97fa700 (LWP 19825)]
[New Thread 0x7fffd87f8700 (LWP 19826)]
[New Thread 0x7fffd7ff7700 (LWP 19827)]
[New Thread 0x7fffd77f6700 (LWP 19828)]
[New Thread 0x7fffd6ff5700 (LWP 19829)]
[New Thread 0x7fffd67f4700 (LWP 19830)]
[New Thread 0x7fffd4cc6700 (LWP 19831)]
Filtered depth-maps 2 (22.22%, 9s, ETA 33s)...[Thread 0x7fffd97fa700 (LWP 19825) exited]
[Thread 0x7fffd6ff5700 (LWP 19829) exited]
[Thread 0x7fffd8ff9700 (LWP 19824) exited]
Filtered depth-maps 5 (55.56%, 9s, ETA 7s)... [Thread 0x7fffd77f6700 (LWP 19828) exited]
Filtered depth-maps 6 (66.67%, 10s, ETA 5s)...[Thread 0x7fffd7ff7700 (LWP 19827) exited]
[Thread 0x7fffd87f8700 (LWP 19826) exited]
[Thread 0x7fffd67f4700 (LWP 19830) exited]
Filtered depth-maps 9 (100%, 11s132ms)          
[Thread 0x7fffd4cc6700 (LWP 19831) exited]
Fused depth-maps 9 (100%, 7s783ms)           

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff4919ab0 in cv::UMatData::~UMatData() () from /usr/local/lib/libopencv_core.so.3.1
(gdb) bt
#0  0x00007ffff4919ab0 in cv::UMatData::~UMatData() () from /usr/local/lib/libopencv_core.so.3.1
#1  0x00007ffff47bc712 in cv::StdMatAllocator::deallocate(cv::UMatData*) const () from /usr/local/lib/libopencv_core.so.3.1
#2  0x00007ffff47bcefc in cv::Mat::deallocate() () from /usr/local/lib/libopencv_core.so.3.1
#3  0x000000000053a179 in SEACAVE::cList<SEACAVE::TImage<SEACAVE::cuint32_t>, SEACAVE::TImage<SEACAVE::cuint32_t> const&, 1, 16, unsigned long>::_Release() [clone .isra.196] ()
#4  0x000000000054bd6b in DepthMapsData::FuseDepthMaps(MVS::PointCloud&, bool) ()
#5  0x00000000005562ae in MVS::Scene::DenseReconstruction() ()
#6  0x000000000052ccb2 in main ()

```

#### Specific commands (assuming you have the folders):
```
./bin/openMVG_main_SfMInit_ImageListing -i images -o outputSIFT -d ~/Downloads/debug/openMVGOxford/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
./bin/openMVG_main_ComputeFeatures -i outReconstructionSIFT/sfm_data.json -o outReconstructionSIFT -f 1
./bin/openMVG_main_ComputeMatches -i outputSIFT/sfm_data.json -o outputSIFT -n BRUTEFORCEL2 -f 1 -r 0.6 ; ./bin/openMVG_main_IncrementalSfM -i outputSIFT/sfm_data.json -m outputSIFT -o outReconstructionSIFT ; ./bin/openMVG_main_ComputeStructureFromKnownPoses -i outReconstructionSIFT/sfm_data.bin -m outputSIFT -o outReconstructionSIFT/robust.ply > outReconstructionSIFT/logComputeStructureFromKnownPoses.txt ; ./bin/openMVG_main_ComputeSfM_DataColor -i outReconstructionSIFT/sfm_data.bin -o outReconstructionSIFT/sfm_data_color.ply ;
openMVG_main_openMVG2openMVS -i outReconstructionSIFT/sfm_data.bin -d images -o outReconstructionLatch/mvs/scene.mvs
DensifyPointCloud -i outReconstructionSIFT/mvs/scene.mvs -o outReconstructionLatch/mvs/scene_dense.mvs

```

Any thoughts? It also happens 2 commits back, when OpenMVS wasn't using the OpenCV pipeline and was instead using its own storage mechanism. I have 32 GB of RAM for 10 images, and I suspect this should be running alright; however, it doesn't seem to be passing the tests.

Thanks in advance,
Matthew Daiter

**Comment by cdcseacave** [comment]
Hi Matthew,
I didn't try it myself, but i noticed the focal length for platform 3 is totally off. Are you sure the openMVG reconstruction is valid?

**Comment by pmoulon** [comment]
Platform 3 does not contains any camera.
Perhaps there is a problem in the OpenMVG2OpenMVS exporter...

**Comment by cdcseacave** [comment]
@pmoulon: I am not sure I understand:
1. if platform 3 does not contain any camera, why does it exist?
2. how do you know there is no camera in platform 3, is there the link to the bin file and I do not see it?

**Comment by pmoulon** [comment]
In the log we can read:
```
Camera model loaded: platform 3; camera  0; f 230416.517x230416.517; poses 0
```

**Comment by cdcseacave** [comment]
Indeed, that is what I was talking about in the first comment: there seems to be a third platform, but no cameras were correctly reconstructed. This is why I was wondering if the reconstruction completed correctly in the first place.

**Comment by mdaiter** [comment]
@cdcseacave The focal length for 3 is totally off! This makes sense - the frame isn't being used after the IncrementalSfM stage.
@pmoulon , any time I recompile OpenMVG (my branch), do I need to recompile the OpenMVG2OpenMVS exporter as well? The exporter broke on compilation due to namespace issues when I started incorporating some OpenCV libraries into my features .hpp files.

**Comment by cdcseacave** [comment]
I'll try reproducing the problem on my side.

**Comment by mdaiter** [comment]
@cdcseacave here are some files, just in case you'd like to inspect them:



[custom.zip](https://github.com/cdcseacave/openMVS/files/358283/custom.zip)

**Comment by cdcseacave** [comment]
found a bug in the fusion step and pushed a fix; is this solving your problem?

**Comment by mdaiter** [comment]
@cdcseacave I'll try it out now. Thanks so much!

**Comment by mdaiter** [comment]
@cdcseacave that push seemed to solve it! Closing now.

**Comment by pmoulon** [comment]
Happy to hear it not linked to the openMVG2openMVS exporter ;-)
