### ISSUE TITLE
DensifyPointCloud error - no depth map generated

### ISSUE THREAD

**Issue by clercj** [cdcseacave/openMVS#113]
Hello, 

I try to densify a point cloud from an openMVG project (openMVG2openMVS export) and as I run DensifyPointCloud, I get some errors listed in the log file attached to the post. The main one is from the reference image. 

[DensifyPointCloud-16082321170500A919.txt](https://github.com/cdcseacave/openMVS/files/433357/DensifyPointCloud-16082321170500A919.txt)

OpenMVS is built on MacOS 10.10.5. 

thanks in advance!

**Comment by cdcseacave** [comment]
Please check that the images are loaded correctly. The log is saying the images have 0 MPixels.

**Comment by clercj** [comment]
Yes, but I would like to know how.

I exported the project with the command
`openMVG_main_openMVG2openMVS -i <INPUTPATH>/sfm_data.bin -o <OUTPUTPATH>/scene.mvs`

The images are automatically saved to the working folder together with the scene.mvs file. So it shouldn't be a problem to load them.
Then I tried with:
`$ /Users/jonasclerc/openMVS_build/bin/DensifyPointCloud -i /Users/jonasclerc/Desktop/Photos/dense/scene.mvs`
but it didn't work, then with

`/Users/jonasclerc/openMVS_build/bin/DensifyPointCloud -i /Users/jonasclerc/Desktop/Photos/dense/scene.mvs -w /Users/jonasclerc/Desktop/Photos/dense`

but it didn't work either. There is something wrong in the .mvs? or in the export function?

**Comment by pmoulon** [comment]
Did you test with another scene in order to check if the problem comes from your dataset?

**Comment by clercj** [comment]
Yes, I've tried it. And it comes to the same problem. My thought is that it comes either from the export or from the compiling of the program. 

I've zipped my files and attached, perhaps you can have a look to the .MVS file or try the densifyPointCloud. (8 images of a gravel pit)

[dense.zip](https://github.com/cdcseacave/openMVS/files/440668/dense.zip)

**Comment by cdcseacave** [comment]
Using the script provided by @FlachyJoe on your dataset like this
```
python MvgMvs_Pipeline.py dense reco
```
I got the following [result](https://skfb.ly/StGV)

**Comment by clercj** [comment]
Well, then I don't even get the script of @FlachyJoe working...

`Using input dir  :  /Users/jonasclerc/Desktop/Photos 2
      output_dir :  /Users/jonasclerc/Desktop/Photos 2/dense
1. Compute features
Traceback (most recent call last):
  File "/Users/jonasclerc/openMVG_Build/MvgMvs_Pipeline.py", line 218, in <module>
    pStep = subprocess.Popen(cmdline)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

I guess there is somewhere a failure in the building or computing. I've followed the thread [https://github.com/cdcseacave/openMVS/issues/89](here) to compile openMVS because I got the same problems...

**Comment by clercj** [comment]
Well, and the InterfaceOpenMVG doesn't work either: 
`MacBook-Pro:~ jonasclerc$ /Users/jonasclerc/openMVS_build/bin/InterfaceOpenMVG -i /Users/jonasclerc/Desktop/Photos/global_out/sfm_data.bin -o /Users/jonasclerc/Desktop/Photos/test/scene.mvs -l /Users/jonasclerc/Desktop/Photos 
21:04:45 [App     ] Build date: Aug 23 2016, 20:27:48
21:04:45 [App     ] CPU: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
21:04:45 [App     ] RAM: 16.00GB Physical Memory 16.00GB Virtual Memory
21:04:45 [App     ] OS: Darwin 14.5.0 (x86_64)
21:04:45 [App     ] SSE & AVX compatible CPU & OS detected
21:04:45 [App     ] Command line: -i /Users/jonasclerc/Desktop/Photos/global_out/sfm_data.bin -o /Users/jonasclerc/Desktop/Photos/test/scene.mvs -l /Users/jonasclerc/Desktop/Photos
21:04:45 [App     ] Reading:
21:04:45 [App     ] /Users/jonasclerc/Desktop/Photos
21:04:45 [App     ] /Users/jonasclerc/Desktop/Photos/global_out/sfm_data.bin
21:04:45 [App     ] Reading BAF file with:
21:04:45 [App     ]  num_intrinsics: 0
21:04:45 [App     ]  num_poses: 32767
21:04:45 [App     ]  num_points: 1758991768
Processed points 1073186196 (61.01%, 5m43s, ETA 3m)...Killed: 9`

**Comment by pmoulon** [comment]
@clercj 
InterfaceOpenMVG is not longer used and have been replaced by a binary in OpenMVG. The new binary that allow to export an OpenMVG scene to OpenMVS is called openMVG_main_openMVG2openMVS.

The crash you observed was located into a OpenMVG binary, in the compute feature step.
Perhaps if your image are too large, you have too much memory allocated. By default the script is using 4 threads. You can try to reduce this number if you see that there is too much memory allocated (change 4 to 2 at this line). (["-i", "%matches_dir%/sfm_data.json", "-o", "%matches_dir%", "-m", "SIFT", "-n", "4"] ],)

**Comment by clercj** [comment]
Well, I've tried the changes you proposed, but it did not change anything. 

Here the complete workflow: [log_mvgmvspipeline.txt](https://github.com/cdcseacave/openMVS/files/448072/log_mvgmvspipeline.txt).

**Comment by pmoulon** [comment]
As @cdcseacave said before, the message that is strange on your computer is the following "8 images (8 calibrated) with a total of 0.00 MPixels (0.00 MPixels/image)"
Seems like the images are not read correctly.

**Comment by FlachyJoe** [comment]
@pmoulon
instead of editing the script you can call it with a 'passthrough' option
 `python MvgMvs_Pipeline.py dense reco --2 n 2`

**Comment by cdcseacave** [comment]
@clercj any progress on this?

**Comment by FlachyJoe** [comment]
I notice the directory path contains a space character, is there any known issue with a such thing under OSX ?
@clercj : Can you please try to rename /Users/jonasclerc/Desktop/Photos 3/ and remove the space ?

**Comment by clercj** [comment]
Sorry, I've got less time to try anything. 

I tried last night the workflow and put a path with no spaces, but the results is the same. 

`8. Densify point cloud
23:34:22 [App     ] Build date: Sep  1 2016, 22:08:41
23:34:22 [App     ] CPU: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
23:34:22 [App     ] RAM: 16.00GB Physical Memory 16.00GB Virtual Memory
23:34:22 [App     ] OS: Darwin 14.5.0 (x86_64)
23:34:22 [App     ] SSE & AVX compatible CPU & OS detected
23:34:22 [App     ] Command line: --input-file /Users/jonasclerc/Desktop/Photos/mvs/scene.mvs --resolution-level 1
23:34:22 [App     ] Camera model loaded: platform 0; camera  0; f 1.134x1.134; poses 8
23:34:22 [App     ] Image loaded   0: SL374124.JPG
23:34:22 [App     ] Image loaded   1: SL374125.JPG
23:34:22 [App     ] Image loaded   2: SL374126.JPG
23:34:22 [App     ] Image loaded   3: SL374127.JPG
23:34:22 [App     ] Image loaded   4: SL374128.JPG
23:34:22 [App     ] Image loaded   5: SL374129.JPG
23:34:22 [App     ] Image loaded   6: SL374130.JPG
23:34:22 [App     ] Image loaded   7: SL374131.JPG
23:34:22 [App     ] Scene loaded from interface format (232ms):
	8 images (8 calibrated) with a total of 0.00 MPixels (0.00 MPixels/image)
	24384 points, 0 vertices, 0 faces
23:34:22 [App     ] Preparing images for dense reconstruction completed: 8 images (0ms)
23:34:22 [App     ] error: reference image   0 has no good images in view
23:34:22 [App     ] error: reference image   1 has no good images in view
23:34:22 [App     ] error: reference image   2 has no good images in view
23:34:22 [App     ] error: reference image   3 has no good images in view
23:34:22 [App     ] error: reference image   4 has no good images in view
23:34:22 [App     ] error: reference image   5 has no good images in view
23:34:22 [App     ] error: reference image   6 has no good images in view
23:34:22 [App     ] error: reference image   7 has no good images in view
23:34:22 [App     ] Selecting images for dense reconstruction completed: 0 images (48ms)
Fused depth-maps 0 (100%, 0ms)
23:34:22 [App     ] Depth-maps fused and filtered: 0 depth-maps, 0 depths, 0 points (-2147483648%%) (0ms)
23:34:22 [App     ] Densifying point-cloud completed: 0 points (54ms)
23:34:22 [App     ] Scene saved (26ms):
	8 images (8 calibrated)
	0 points, 0 vertices, 0 faces
`

I will recompile openMVS and put the whole process here, perhaps you see some issues in the compilation process.

**Comment by cdcseacave** [comment]
it seems there is a problem with the JPEG library and the images are not loaded (0.00 MPixels), please make sure that during compilation the JPEG library is found and set

**Comment by FlachyJoe** [comment]
Be sure the dev headers are in the same version of the lib!
In some cases CMake finds headers in /usr/local/includes but link with the system lib in /usr/lib. It causes a version mismatch when launched.

**Comment by clercj** [comment]
So, I recompiled openMVS. 

Here the complete workflow:

[compilation_log.txt](https://github.com/cdcseacave/openMVS/files/478910/compilation_log.txt)

Maybe you find something interesting. 

How do I check the dev headers?

**Comment by cdcseacave** [comment]
from this log file it is not possible to see if the JPEG library used to compile OpenMVS is the same used to compile openCV... make sure the same version is used (for instance open both projects with cmake-gui and check, or add a verbosity message to .cmake project to print the include paths, etc)

**Comment by sunguangjiang** [comment]
opemMVG:
`// write OpenMVS data
  if (!ARCHIVE::SerializeSave(scene, sOutFile))
    return false;`
openMVS:
`// load project version
	uint32_t nVer;
	fs.read((char*)&nVer, sizeof(uint32_t));
	if (!fs || nVer != PROJECT_VER) {
		VERBOSE("error: different project version");
		return false;
	}
	// load stream type
	uint32_t nType = ARCHIVE_BINARY;
	fs.read((char*)&nType, sizeof(uint32_t));
	// skip reserved bytes
	uint64_t nReserved;
	fs.read((char*)&nReserved, sizeof(uint64_t));
	// serialize in the current state
	if (!SerializeLoad(*this, fs, (ARCHIVE_TYPE)nType))`
**format is inconformity!**

**Comment by cdcseacave** [comment]
Closing as stale. The OpenMVS codebase has undergone extensive refactoring and modernisation on the \develop\ branch since this issue was opened. If you believe this is still relevant, please test against the latest \develop\ branch and open a new issue with reproduction steps.
