### ISSUE TITLE
bad_alloc running graph-cut and extracting mesh

### ISSUE THREAD

**Issue by charlescva** [cdcseacave/openMVS#171]
### Specifications like the version of the project, operating system, and hardware
Build from commit fa0c2d8be6847d3185827f650ce7a202bb8a44e1
Author: cdcseacave <cdc.seacave@gmail.com>
Date:   Sat Nov 5 21:45:26 2016 -0700

root@a9d119874f31:/openMVS# uname -a
Linux a9d119874f31 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
root@a9d119874f31:/openMVS# gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

### Steps to reproduce the problem
ReconstructMesh reconstruction_dense.mvs

> root@a9d119874f31:/home/output# ReconstructMesh reconstruction_dense.mvs 
> 15:13:42 [App     ] Build date: Jan 27 2017, 15:11:06
> 15:13:42 [App     ] CPU: Intel(R) Xeon(R) CPU           X5680  @ 3.33GHz
> 15:13:42 [App     ] RAM: 39.12GB Physical Memory 0B Virtual Memory
> 15:13:42 [App     ] OS: Linux 3.10.0-514.6.1.el7.x86_64 (x86_64)
> 15:13:42 [App     ] warning: no AVX compatible CPU or OS detected
> 15:13:42 [App     ] Command line: reconstruction_dense.mvs
> 15:14:18 [App     ] Scene loaded (35s936ms):
>         249 images (249 calibrated) with a total of 356.20 MPixels (1.43 MPixels/image)
>         29246608 points, 0 vertices, 0 faces
> 15:19:49 [App     ] Delaunay tetrahedralization completed: 29246608 points -> 27045036 vertices, 178320393 (+236) cell
> s, 356640904 (+354) faces (5m19s228ms)
> 15:25:23 [App     ] Delaunay tetrahedras weighting completed: 178320629 cells, 356641258 faces (5m30s61ms)
> terminate called after throwing an instance of 'std::bad_alloc'
>   what():  std::bad_alloc
> Aborted (core dumped)

Analysis of the core dump showed, 

```

> #0  0x00007f789072d428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
> #1  0x00007f789072f02a in __GI_abort () at abort.c:89
> #2  0x00007f789106f84d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
> #3  0x00007f789106d6b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
> #4  0x00007f789106d701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
> #5  0x00007f789106d919 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
> #6  0x00007f789106debc in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
> #7  0x00007f789106df19 in operator new[](unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
> #8  0x00000000005b7d5b in IBFS::IBFSGraph::initSize(int, int) ()
> #9  0x00000000005b2a21 in MVS::Scene::ReconstructMesh(float, bool, unsigned int, float, float, float, float, float, float, float, float) ()
> #10 0x00000000005074f6 in main ()

```

Encapsulated Debug statements around the create graph portion and re-executed...

```
                DEBUG_EXTRA("Creating Graph from %u Cells...", delaunay.number_of_cells());
                MaxFlow<cell_size_t,edge_cap_t> graph(delaunay.number_of_cells());
                DEBUG_EXTRA("Setting Weights on all Cells...");
```

> 15:25:23 [App     ] Delaunay tetrahedras weighting completed: 178320629 cells, 356641258 faces (5m30s61ms)
> 15:25:24 [App     ] Creating Graph from 178320629 Cells...
> terminate called after throwing an instance of 'std::bad_alloc'
>   what():  std::bad_alloc
> Aborted (core dumped)

Result is that it is having exception at graph creation.

**Comment by charlescva** [comment]
So my best guess is that I don't have enough memory to alloc a IBFSGraph type with 178,320,629 cells...

Just a question or two here...

1.) Is there a way to 'chunk' this without rewriting the IBFS max flow solver?  Doubtfull I have the witts for such an undertaking. So, I'm guessing the proper way to batch it is to attempt a scene reconstruction in subsets and merge final models later...

2.) I was hitting my memory cap with DensifyPointCloud as well but resolved it by passing the --resolution-level arg as 2 instead of the default of 1.  If I were to attempt a resolution level arg as 3, would that actually help with this memory issue?

3.) There is a quality factor arg for Reconstruct Options, Would this help or am I just going to fail instantiating the graph again anyway?

Thanks!

**Comment by charlescva** [comment]
Okay, I was able to find a work around using one of the flags provided:

 -d [ --min-point-distance ] arg (=2)  minimum distance in pixels between the 
                                        projection of two 3D points to consider
                                        them different while triangulating (0 -
                                        disabled)

Setting it higher reduces number of cells created, and also mesh resolution.
