### ISSUE TITLE
Segfault with ReconstructMesh

### ISSUE THREAD

**Issue by WeiGuaa** [cdcseacave/openMVS#877]
**Describe the bug**
ReconstructMesh threw an exception with segment error when processing dense.mvs

**To Reproduce**
run  "/usr/local/bin/OpenMVS/ReconstructMesh ./birdscene_dense.mvs"

**Expected behavior**
I want to generate dense_mesh.mvs  through ReconstructMesh of script, but happening the Segmentation fault.

**Screenshots**
```
13:41:25 [App     ] Build date: Oct  8 2022, 12:31:32
13:41:25 [App     ] CPU: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 cores)
13:41:25 [App     ] RAM: 15.49GB Physical Memory 15.26GB Virtual Memory
13:41:25 [App     ] OS: Linux 5.15.0-48-generic (x86_64)
13:41:25 [App     ] Disk: 840.51GB (915.82GB) space
13:41:25 [App     ] SSE & AVX compatible CPU & OS detected
13:41:25 [App     ] Command line: ReconstructMesh ./birdscene_dense.mvs
13:41:25 [App     ] Scene loaded (0ms):
	11 images (11 calibrated) with a total of 31.98 MPixels (2.91 MPixels/image)
	0 points, 0 vertices, 0 faces
Points inserted 0 (100%, 0ms)
Segmentation fault (core dumped)
```

```
(gdb) bt
#0  0x00005570437b071c in void DELAUNAY::fetchCellFacets<1>(CGAL::Delaunay_triangulation_3<CGAL::Epick, CGAL::Triangulation_data_structure_3<CGAL::Triangulation_vertex_base_with_info_3<DELAUNAY::vert_info_t, CGAL::Epick, CGAL::Triangulation_vertex_base_3<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_3<void> > >, CGAL::Triangulation_cell_base_with_info_3<unsigned int, CGAL::Epick, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<void> > >, CGAL::Sequential_tag>, CGAL::Location_policy<CGAL::Compact>, CGAL::Default> const&, std::vector<std::pair<CGAL::internal::CC_iterator<CGAL::Compact_container<CGAL::Triangulation_cell_base_with_info_3<unsigned int, CGAL::Epick, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<CGAL::Triangulation_data_structure_3<CGAL::Triangulation_vertex_base_with_info_3<DELAUNAY::vert_info_t, CGAL::Epick, CGAL::Triangulation_vertex_base_3<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_3<void> > >, CGAL::Triangulation_cell_base_with_info_3<unsigned int, CGAL::Epick, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<void> > >, CGAL::Sequential_tag> > > >, CGAL::Default, CGAL::Default, CGAL::Default>, false>, int>, std::allocator<std::pair<CGAL::internal::CC_iterator<CGAL::Compact_container<CGAL::Triangulation_cell_base_with_info_3<unsigned int, CGAL::Epick, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<CGAL::Triangulation_data_structure_3<CGAL::Triangulation_vertex_base_with_info_3<DELAUNAY::vert_info_t, CGAL::Epick, CGAL::Triangulation_vertex_base_3<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_3<void> > >, CGAL::Triangulation_cell_base_with_info_3<unsigned int, CGAL::Epick, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<void> > >, CGAL::Sequential_tag> > > >, CGAL::Default, CGAL::Default, CGAL::Default>, false>, int> > > const&, CGAL::internal::CC_iterator<CGAL::Compact_container<CGAL::Triangulation_cell_base_with_info_3<unsigned int, CGAL::Epick, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<CGAL::Triangulation_data_structure_3<CGAL::Triangulation_vertex_base_with_info_3<DELAUNAY::vert_info_t, CGAL::Epick, CGAL::Triangulation_vertex_base_3<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_3<void> > >, CGAL::Triangulation_cell_base_with_info_3<unsigned int, CGAL::Epick, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<void> > >, CGAL::Sequential_tag> > > >, CGAL::Default, CGAL::Default, CGAL::Default>, false> const&, MVS::Image const&, std::vector<std::pair<CGAL::internal::CC_iterator<CGAL::Compact_container<CGAL::Triangulation_cell_base_with_info_3<unsigned int, CGAL::Epick, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<CGAL::Triangulation_data_structure_3<CGAL::Triangulation_vertex_base_with_info_3<DELAUNAY::vert_info_t, CGAL::Epick, CGAL::Triangulation_vertex_base_3<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_3<void> > >, CGAL::Triangulation_cell_base_with_info_3<unsigned int, CGAL::Epick, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<void> > >, CGAL::Sequential_tag> > > >, CGAL::Default, CGAL::Default, CGAL::Default>, false>, int>, std::allocator<std::pair<CGAL::internal::CC_iterator<CGAL::Compact_container<CGAL::Triangulation_cell_base_with_info_3<unsigned int, CGAL::Epick, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<CGAL::Triangulation_data_structure_3<CGAL::Triangulation_vertex_base_with_info_3<DELAUNAY::vert_info_t, CGAL::Epick, CGAL::Triangulation_vertex_base_3<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_3<void> > >, CGAL::Triangulation_cell_base_with_info_3<unsigned int, CGAL::Epick, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<void> > >, CGAL::Sequential_tag> > > >, CGAL::Default, CGAL::Default, CGAL::Default>, false>, int> > >&) ()
#1  0x00005570437d14a3 in MVS::Scene::ReconstructMesh(float, bool, bool, unsigned int, float, float, float, float, float, float, float, float) ()
#2  0x000055704364b969 in main ()
```

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
```
-- Detected version of GNU GCC: 94 (904)
Compiling with C++17
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Can't find CUDA. Continuing without it.
-- WARNING: BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
-- Can't find BreakPad. Continuing without it.
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: iostreams program_options system serialization 
-- Eigen 3.4.0 found (include: /usr/local/include/eigen3)
-- OpenCV 4.2.0 found (include: /usr/include/opencv4)
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.48")  
-- Boost include dirs: /usr/include
-- Boost libraries:    
-- Using gcc version 4 or later. Adding -frounding-math
-- VCG  found (include: /home/wei/vcglib)
-- GLEW 2.1.0 found (include: /usr/include)
-- GLFW3 3.3.2 found (include: )
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wei/openMVS_build
```

**Additional context**

**Comment by cdcseacave** [comment]
your scene is empty, what to reconstruct?
```
0 points, 0 vertices, 0 faces
```

**Comment by WeiGuaa** [comment]
> your scene is empty, what to reconstruct?
> 
> ```
> 0 points, 0 vertices, 0 faces
> ```

Thank you, I was too careless.The generation of openMVG is empty.
