### ISSUE TITLE
Add openMVS to Homebrew (macOS package manager)

### ISSUE THREAD

**Issue by verhovsky** [cdcseacave/openMVS#924]
I tried adding openMVS to Homebrew

https://github.com/verhovsky/homebrew-core/commit/9e469ca2288a6ea5791cd890750ae943d0c95ce9

but I couldn't figure out the last step, how to get it to run `xcodebuild`, I get this error after running `brew install --build-from-source --debug --verbose openmvs` with the changes in that commit:

```
==> xcodebuild -configuration Release SYMROOT=build -arch arm64
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -configuration Release SYMROOT=build -arch arm64

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Build settings from command line:
    ARCHS = arm64
    SYMROOT = build

Computing target dependency graph and provisioning inputs
2023-01-09 17:04:40.086 xcodebuild[30517:13608537] Error: stepSQLStatement:toCompletionWithRetry - stepping returned unhandled result=8, DB=/Users/space/Library/Caches/com.apple.dt.xcodebuild/Cache.db

Create build description
Build description signature: 07cbcbe72768976931b28e0d29214069
Build description path: /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/XCBuildData/07cbcbe72768976931b28e0d29214069-desc.xcbuild

warning: Building targets in manual order is deprecated - check "Parallelize build for command-line builds" in the project editor, or set DISABLE_MANUAL_TARGET_ORDER_BUILD_WARNING in any of the targets in the current build to suppress this warning
CreateBuildDirectory /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build
    cd /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/OpenMVS.xcodeproj
    builtin-create-build-directory /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build

CreateBuildDirectory /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/Release
    cd /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/OpenMVS.xcodeproj
    builtin-create-build-directory /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/Release

CreateBuildDirectory /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/EagerLinkingTBDs
    cd /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/OpenMVS.xcodeproj
    builtin-create-build-directory /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/EagerLinkingTBDs

CreateBuildDirectory /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/bin/Release
    cd /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/OpenMVS.xcodeproj
    builtin-create-build-directory /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/bin/Release

CreateBuildDirectory /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/lib/Release
    cd /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/OpenMVS.xcodeproj
    builtin-create-build-directory /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/lib/Release

note: Run script build phase 'Generate CMakeFiles/ZERO_CHECK' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ZERO_CHECK' from project 'OpenMVS')
WriteAuxiliaryFile /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/OpenMVS.build/Release/ZERO_CHECK.build/Script-0981A7F106D73762FB3F8ADC.sh (in target 'ZERO_CHECK' from project 'OpenMVS')
    cd /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0
    write-file /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/OpenMVS.build/Release/ZERO_CHECK.build/Script-0981A7F106D73762FB3F8ADC.sh

PhaseScriptExecution Generate\ CMakeFiles/ZERO_CHECK /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/OpenMVS.build/Release/ZERO_CHECK.build/Script-0981A7F106D73762FB3F8ADC.sh (in target 'ZERO_CHECK' from project 'OpenMVS')
    cd /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0
    /bin/sh -c /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/OpenMVS.build/Release/ZERO_CHECK.build/Script-0981A7F106D73762FB3F8ADC.sh
make: `/tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/CMakeFiles/cmake.check_cache' is up to date.

ProcessPCH++ /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/SharedPrecompiledHeaders/SharedPrecompiledHeaders/12818551680565275431/cmake_pch.hxx.gch /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/libs/Common/CMakeFiles/Common.dir/Release/cmake_pch.hxx normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Common' from project 'OpenMVS')
    cd /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0
    
    Precompile of '/tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/libs/Common/CMakeFiles/Common.dir/Release/cmake_pch.hxx' required by '/tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/libs/Common/Common.cpp'
    
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++-header -target arm64-apple-macos13.0 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -stdlib\=libc++ -Wno-trigraphs -fpascal-strings -O3 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -Wno-implicit-fallthrough -DCMAKE_INTDIR\=\"Release\" -D_LIB -D_USE_OPENMP -D_USE_OPENGL -D_USE_BOOST -D_USE_EIGEN -D_USE_NONFREE -D_USE_FAST_FLOAT2INT -D_USE_FAST_CBRT -D_USE_SSE -DBOOST_IOSTREAMS_NO_LIB -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_SYSTEM_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SERIALIZATION_NO_LIB -DBOOST_SERIALIZATION_DYN_LINK -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body -I/tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/lib/Release/include -I/opt/homebrew/include/eigen3 -I/tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0 -I/tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build -isystem /opt/homebrew/Cellar/opencv/4.6.0_1/include/opencv4 -I/tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/build/Common.build/Release/DerivedSources-normal/arm64 -I/tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/build/Common.build/Release/DerivedSources/arm64 -I/tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/build/Common.build/Release/DerivedSources -F/tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/lib/Release -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.sdk/System/Library/Frameworks -W -Werror\=address -Werror\=sequence-point -Wformat -Werror\=format-security -Winit-self -Wsign-promo -Wreorder -Wno-undef -Wno-switch -Wno-switch-enum -Wno-switch-default -Wno-implicit-fallthrough -Wno-comment -Wno-narrowing -Wno-attributes -Wno-ignored-attributes -Wno-enum-compare -Wno-misleading-indentation -Wno-missing-field-initializers -Wno-unused-result -Wno-unused-function -Wno-unused-parameter -Wno-delete-incomplete -Wno-unnamed-type-template-args -Wno-int-in-bool-context -fdiagnostics-show-option -ftemplate-backtrace-limit\=0 -pthread -fno-omit-frame-pointer -Xclang -fopenmp -DNDEBUG -DNDEBUG -std\=c++17 -c /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/libs/Common/CMakeFiles/Common.dir/Release/cmake_pch.hxx -MD -MT dependencies -MF /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/SharedPrecompiledHeaders/SharedPrecompiledHeaders/12818551680565275431/cmake_pch.hxx.d -I/tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/lib/Release/include -I/opt/homebrew/include/eigen3 -I/tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0 -I/tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build -isystem /opt/homebrew/Cellar/opencv/4.6.0_1/include/opencv4 -I/tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/build/Common.build/Release/DerivedSources-normal/arm64 -I/tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/build/Common.build/Release/DerivedSources/arm64 -I/tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/build/Common.build/Release/DerivedSources -o /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/SharedPrecompiledHeaders/SharedPrecompiledHeaders/12818551680565275431/cmake_pch.hxx.gch --serialize-diagnostics /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/SharedPrecompiledHeaders/SharedPrecompiledHeaders/12818551680565275431/cmake_pch.hxx.dia
In file included from /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/libs/Common/CMakeFiles/Common.dir/Release/cmake_pch.hxx:4:
In file included from /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/libs/Common/Common.h:176:
/tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/libs/Common/Types.h:71:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.

WriteAuxiliaryFile /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/build/Common.build/Release/Objects-normal/arm64/Common.LinkFileList (in target 'Common' from project 'OpenMVS')
    cd /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0
    write-file /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/build/Common.build/Release/Objects-normal/arm64/Common.LinkFileList

note: Run script build phase 'Generate CMakeFiles/ALL_BUILD' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ALL_BUILD' from project 'OpenMVS')
** BUILD FAILED **


The following build commands failed:
	ProcessPCH++ /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/SharedPrecompiledHeaders/SharedPrecompiledHeaders/12818551680565275431/cmake_pch.hxx.gch /tmp/openmvs-20230109-29558-105tjis/openMVS-2.1.0/build/libs/Common/CMakeFiles/Common.dir/Release/cmake_pch.hxx normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Common' from project 'OpenMVS')
(1 failure)
/opt/homebrew/Library/Homebrew/shims/shared/git --version
/opt/homebrew/Library/Homebrew/shims/shared/curl --version
/opt/homebrew/Library/Homebrew/ignorable.rb:29:in `block in raise'
```

I'm leaving a link here to my attempt in case someone wants to finish it. `std_cmake_args` can be found [here](https://github.com/Homebrew/brew/blob/a73e2c679c3a935f21df80179fe7ac62c3c93f85/Library/Homebrew/formula.rb#L1540).

**Comment by verhovsky** [comment]
I was able to build OpenMVS locally on my M1 Mac with these instructions: https://github.com/cdcseacave/openMVS/issues/921#issuecomment-1495914351

Trying to get it to work through homebrew is harder, I fixed the import errors with ChatGTP + GPT4's help

https://github.com/verhovsky/homebrew-core/commit/710a03f3f066683e56ec75ffd5a510f313ebcb03

https://github.com/verhovsky/homebrew-core/tree/openmvs

but now I'm stuck on this error, which seems to be about COLMAP, we can't install it through homebrew because it hasn't been signed (and I wouldn't hold my breath) and I don't know how to disable compiling for it.

```
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target arm64-apple-macos13.0 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -stdlib\=libc++ -Wno-trigraphs -fpascal-strings -O3 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -Wno-implicit-fallthrough -DCMAKE_INTDIR\=\"Release\" -D_LIB -D_USE_OPENMP -D_USE_OPENGL -D_USE_BOOST -D_USE_EIGEN -D_USE_NONFREE -D_USE_FAST_FLOAT2INT -D_USE_FAST_CBRT -D_USE_PNG -D_USE_JPG -D_USE_TIFF -DBOOST_IOSTREAMS_NO_LIB -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_SYSTEM_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SERIALIZATION_NO_LIB -DBOOST_SERIALIZATION_DYN_LINK -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body -I/tmp/openmvs-20230404-820-1m40uzk/openMVS-2.1.0/build/lib/Release/include -I/opt/homebrew/opt/eigen/include/eigen3 -I/tmp/openmvs-20230404-820-1m40uzk/openMVS-2.1.0 -I/tmp/openmvs-20230404-820-1m40uzk/openMVS-2.1.0/build -isystem /opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4 -I/tmp/openmvs-20230404-820-1m40uzk/openMVS-2.1.0/build/build/IO.build/Release/DerivedSources-normal/arm64 -I/tmp/openmvs-20230404-820-1m40uzk/openMVS-2.1.0/build/build/IO.build/Release/DerivedSources/arm64 -I/tmp/openmvs-20230404-820-1m40uzk/openMVS-2.1.0/build/build/IO.build/Release/DerivedSources -F/tmp/openmvs-20230404-820-1m40uzk/openMVS-2.1.0/build/lib/Release -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.sdk/System/Library/Frameworks -W -Werror\=address -Werror\=sequence-point -Wformat -Werror\=format-security -Winit-self -Wsign-promo -Wreorder -Wno-undef -Wno-switch -Wno-switch-enum -Wno-switch-default -Wno-implicit-fallthrough -Wno-comment -Wno-narrowing -Wno-attributes -Wno-ignored-attributes -Wno-enum-compare -Wno-misleading-indentation -Wno-missing-field-initializers -Wno-unused-result -Wno-unused-function -Wno-unused-parameter -Wno-delete-incomplete -Wno-unnamed-type-template-args -Wno-int-in-bool-context -fdiagnostics-show-option -ftemplate-backtrace-limit\=0 -pthread -fno-omit-frame-pointer -Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include -I/opt/homebrew/opt/boost/include -I/opt/homebrew/opt/libpng/include -I/opt/homebrew/opt/jpeg/include -DNDEBUG -DNDEBUG -std\=c++17 -include /tmp/openmvs-20230404-820-1m40uzk/openMVS-2.1.0/build/SharedPrecompiledHeaders/SharedPrecompiledHeaders/10765027139045622471/cmake_pch.hxx -MMD -MT dependencies -MF /tmp/openmvs-20230404-820-1m40uzk/openMVS-2.1.0/build/build/IO.build/Release/Objects-normal/arm64/ImageDDS.d --serialize-diagnostics /tmp/openmvs-20230404-820-1m40uzk/openMVS-2.1.0/build/build/IO.build/Release/Objects-normal/arm64/ImageDDS.dia -c /tmp/openmvs-20230404-820-1m40uzk/openMVS-2.1.0/libs/IO/ImageDDS.cpp -o /tmp/openmvs-20230404-820-1m40uzk/openMVS-2.1.0/build/build/IO.build/Release/Objects-normal/arm64/ImageDDS.o

note: Run script build phase 'Generate CMakeFiles/ALL_BUILD' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ALL_BUILD' from project 'OpenMVS')
** BUILD FAILED **


The following build commands failed:
	CompileC /tmp/openmvs-20230404-820-1m40uzk/openMVS-2.1.0/build/build/IO.build/Release/Objects-normal/arm64/ImageTIFF.o /tmp/openmvs-20230404-820-1m40uzk/openMVS-2.1.0/libs/IO/ImageTIFF.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'IO' from project 'OpenMVS')
(1 failure)
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/git --version
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --version
/opt/homebrew/Library/Homebrew/ignorable.rb:29:in `block in raise'
BuildError: Failed executing: xcodebuild -configuration Release SYMROOT=build -arch arm64
```

**Comment by cdcseacave** [comment]
Homebrew packaging is outside the scope of this project. Community contributions are welcome.
